#!/usr/bin/env python3

import tempfile
import os
from pathlib import Path
import re
import sys

# Create content that is actually generated by the function itself
scripts_dir = Path(__file__).parent / "scripts"
sys.path.insert(0, str(scripts_dir))

import importlib.util
spec = importlib.util.spec_from_file_location("cmb_debit_auto_analysis", scripts_dir / "cmb-debit-auto-analysis.py")
cmb_debit_auto_analysis = importlib.util.module_from_spec(spec)
sys.modules["cmb_debit_auto_analysis"] = cmb_debit_auto_analysis
spec.loader.exec_module(cmb_debit_auto_analysis)

# Generate a real report to use as test data
transactions = [
    cmb_debit_auto_analysis.Transaction("9583", "03/13", "09:44", "快捷支付", "支付宝-蚂蚁基金", 10.0, 4506.81, ""),
    cmb_debit_auto_analysis.Transaction("9583", "03/12", None, "定投扣款", "嘉实沪深300", 1000.0, 5506.81, ""),
]

real_report = cmb_debit_auto_analysis.generate_report(transactions)

# Save to a temporary file and test the actual function
with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.md', encoding='utf-8') as f:
    f.write(real_report)
    temp_file_path = f.name

print("Testing the actual parse_existing_transactions function with generated report...")
try:
    result = cmb_debit_auto_analysis.parse_existing_transactions(Path(temp_file_path))
    print(f"Success! Function returned {len(result)} transactions")
    for i, trans in enumerate(result):
        print(f"  Transaction {i+1}: {trans.date} {trans.time} {trans.account} {trans.transaction_type} '{trans.description}' {trans.amount} {trans.balance}")

    # Verify that we get the expected transactions back
    if len(result) == 2:
        expected1 = {"date": "03/13", "time": "09:44", "account": "9583", "type": "快捷支付", "desc": "支付宝-蚂蚁基金", "amount": 10.0}
        expected2 = {"date": "03/12", "time": None, "account": "9583", "type": "定投扣款", "desc": "嘉实沪深300", "amount": 1000.0}

        # Check first transaction
        t1 = result[0]
        if (t1.date == expected1["date"] and t1.time == expected1["time"] and
            t1.account == expected1["account"] and t1.transaction_type == expected1["type"] and
            t1.description == expected1["desc"] and t1.amount == expected1["amount"]):
            print("  ✓ First transaction matches expected")
        else:
            print(f"  ✗ First transaction mismatch: {t1.__dict__} vs {expected1}")

        # Check second transaction
        t2 = result[1]
        if (t2.date == expected2["date"] and t2.time == expected2["time"] and
            t2.account == expected2["account"] and t2.transaction_type == expected2["type"] and
            t2.description == expected2["desc"] and t2.amount == expected2["amount"]):
            print("  ✓ Second transaction matches expected")
        else:
            print(f"  ✗ Second transaction mismatch: {t2.__dict__} vs {expected2}")
    else:
        print(f"  ✗ Expected 2 transactions, got {len(result)}")

finally:
    os.unlink(temp_file_path)

print()
print("Now checking if there might be a Python environment issue with the regex...")

# Check if the issue is Python version specific or related to re module
print(f"Python version: {sys.version}")

# Let's try to isolate the problem in the function code by recreating it with a more robust pattern
print()
print("Testing whether the issue might be with the actual regex in the source function...")

# Let's create an isolated version that works around the emoji issue
def test_pattern_with_fallback(content):
    """Test version that tries different patterns"""
    # Original pattern from the code
    original_pattern = r'\|\s*(\d{2}/\d{2})\s*\|\s*(-|\d{2}:\d{2})\s*\|\s*(\d{4})\s*\|\s*(💳 快捷支付|💰 定投扣款)\s*\|\s*(.+?)\s*\|\s*-¥([\d,]+)\s*\|\s*¥([\d,]+)\s*\|'

    matches1 = list(re.finditer(original_pattern, content))
    print(f"Original pattern found: {len(matches1)} matches")

    # Alternative pattern using character ranges
    alt_pattern = r'\|\s*(\d{2}/\d{2})\s*\|\s*(-|\d{2}:\d{2})\s*\|\s*(\d{4})\s*\|\s*([^\|]*?(?:快捷支付|定投扣款))\s*\|\s*(.+?)\s*\|\s*-¥([\d,]+)\s*\|\s*¥([\d,]+)\s*\|'

    matches2 = list(re.finditer(alt_pattern, content))
    print(f"Alternative pattern found: {len(matches2)} matches")

    return matches1, matches2

matches1, matches2 = test_pattern_with_fallback(real_report)
print(f"Pattern comparison: Original={len(matches1)}, Alternative={len(matches2)}")

if matches1:
    for i, match in enumerate(matches1):
        print(f"  Original match {i+1}: {match.groups()}")
elif matches2:
    for i, match in enumerate(matches2):
        print(f"  Alternative match {i+1}: {match.groups()}")
else:
    print("  No matches with either pattern!")

    # Let's try with re.UNICODE flag
    import re
    unicode_matches = list(re.finditer(original_pattern, real_report, re.UNICODE))
    print(f"With UNICODE flag: {len(unicode_matches)} matches")

    for i, match in enumerate(unicode_matches):
        print(f"  UNICODE match {i+1}: {match.groups()}")